name: GitHub Pages 배포

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 코드
        uses: actions/checkout@v4

      - name: GitHub Pages 설정
        uses: actions/configure-pages@v4

      - name: 정적 아티팩트 업로드
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: GitHub Pages 배포
        id: deployment
        uses: actions/deploy-pages@v4
